services:
  - type: web
    name: sports-news
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/huggingface
